### ISSUE TITLE
Not working on Chrome and Brave

### ISSUE THREAD

**Issue by vinismarques** [searchmarkers/mark-my-search#135] opened 2023-06-21 14:48 UTC
I tested it on both Chrome and Brave, and it isn't working. I'm unable to choose which matching strategy I want (stem, whole words, case sensitive, etc.). No matter which option I try to select, it isn't activated. This is happening across all pages I tested with.

In Firefox it is working fine.

If you have issues reproducing just let me know.

**Comment by ator-dev** [comment] 2023-06-21 16:24
Hi, thanks for reporting. I have never noticed an issue of this kind, and cannot reproduce on Chrome, Edge, or Brave. Were these old installs of the extension, which may have broken after an update?

---

If you're definitely on the latest version (1.14.2), would you mind carry out some quick debugging steps please? You'll need to go to `about:extensions` and turn developer mode on.

![image](https://github.com/searchmarkers/mark-my-search/assets/66553618/6455c059-199f-4aa4-9363-3895e8af1072)

Under Mark My Search, click "service worker" in the "Inspect views" field. The dev tools should open; make sure you're on the "Console" tab. There should be only logs and no errors if things are running smoothly.

If there are no obvious errors or warnings, try clearing the Console with Ctrl+L, and then perform an action that *fails*.

A successful matching strategy change will look like this:

![image](https://github.com/searchmarkers/mark-my-search/assets/66553618/d67ad4e6-174a-4486-bac2-a0042d1f5b56)

A successful search request will print a lot more information, but it should include all of these messages:

![image](https://github.com/searchmarkers/mark-my-search/assets/66553618/608a7d77-3f3d-4189-9004-d80c9450c6c5)

**Comment by ator-dev** [comment] 2023-06-21 16:27
I forgot to mention; please send a screenshot of what happens. It should include enough information for me to diagnose the problem!

**Comment by vinismarques** [comment] 2023-06-22 02:17
I wasn't sure if a screenshot would have all the necessary information, so here is an export of the logs.

First I cleaned the console, then searched for "Mention" and tried to enable different matching "engines" (whole word, stem, regex, case sensitive), but no matter which option I chose, on console, I could see that `matchMode` values remained the same.

[console-1687399780022.log](https://github.com/searchmarkers/mark-my-search/files/11828010/console-1687399780022.log)

**Comment by ator-dev** [comment] 2023-06-23 22:06
Sorry for the delay, and thanks for the logs! I have narrowed down where the problem could be, but I can't tell yet why it might be failing to update the terms.

Actually, the logging is a bit deceptive: the pair of logs will have the same `matchMode` object but with an updated field, if it worked correctly. From your console file, the backend seems to be working correctly.

![image](https://github.com/searchmarkers/mark-my-search/assets/66553618/e615333e-2eb8-438a-9163-4203e2b961a7)

Firstly, to make sure, is the extension version definitely 1.14.2? And if you *refresh* the page after changing the matching strategy, are your choices retained (and apply to the page)?

Secondly, could you try exporting your extension settings please? This will let me test locally. I don't have a standard way yet, but if you open the console again and then enter the following:

```js
await storageGet("local")
await storageGet("sync")
```

You can right click on the result and "Copy object" in order to paste it in here. Don't worry; there's nothing identifiable stored there, only some basic config.

Sorry for the inconvenience (:

**Comment by vinismarques** [comment] 2023-06-26 13:25
Yep, I'm on 1.14.2. I even tried reinstalling it, but it didn't help.

![image](https://github.com/searchmarkers/mark-my-search/assets/33668018/2ca74237-0484-4c92-a810-bcab26276acb)

So, I tried doing a simple test: cleaning the extension's Console and refreshing a page I already had text searched and modifying match mode to Case Sensitive. I noticed that the interface didn't change at all, but at the backend, there seem to be mixed values for `case` instead of only `true` (the last one being `false`).

The interface isn't being modified. Doesn't matter which match mode I select, it always stays the same: 
![image](https://github.com/searchmarkers/mark-my-search/assets/33668018/dddf852c-41ed-4c89-a4ac-b8abf6895bc9)

Here are the logs:
[console-1687785199505.log](https://github.com/searchmarkers/mark-my-search/files/11869338/console-1687785199505.log)

Note that the log was generated after clicking only once to enable case sensitivity.

### Extension settings

```
{
    "enabled": true,
    "followLinks": true,
    "persistResearchInstances": true
}
```

```
{
    "autoFindOptions": {
        "searchParams": [
            "search_terms",
            "search_term",
            "searchTerms",
            "searchTerm",
            "search_query",
            "searchQuery",
            "search",
            "query",
            "phrase",
            "keywords",
            "keyword",
            "terms",
            "term",
            "text",
            "s",
            "q",
            "p",
            "k",
            "_nkw",
            "wd"
        ],
        "stoplist": [
            "i",
            "a",
            "an",
            "and",
            "or",
            "not",
            "the",
            "that",
            "there",
            "where",
            "which",
            "to",
            "do",
            "of",
            "in",
            "on",
            "at",
            "too",
            "if",
            "for",
            "while",
            "is",
            "as",
            "isn't",
            "are",
            "aren't",
            "can",
            "can't",
            "how",
            "vs",
            "them",
            "their",
            "theirs",
            "her",
            "hers",
            "him",
            "his",
            "it",
            "its",
            "me",
            "my",
            "one",
            "one's",
            "you",
            "your",
            "yours"
        ]
    },
    "barCollapse": {
        "fromSearch": false,
        "fromTermListAuto": false
    },
    "barControlsShown": {
        "appendTerm": true,
        "disableTabResearch": true,
        "performSearch": false,
        "replaceTerms": true,
        "toggleBarCollapsed": true,
        "toggleHighlights": true
    },
    "barLook": {
        "borderRadius": "4px",
        "fontSize": "14.6px",
        "opacityControl": 0.8,
        "opacityTerm": 0.86,
        "showEditIcon": true,
        "showRevealIcon": true
    },
    "highlightMethod": {
        "hues": [
            300,
            60,
            110,
            220,
            30,
            190,
            0
        ],
        "paintReplaceByClassic": true,
        "paintUseExperimental": false
    },
    "matchModeDefaults": {
        "case": false,
        "diacritics": false,
        "regex": false,
        "stem": true,
        "whole": false
    },
    "showHighlights": {
        "default": true,
        "overrideResearchPages": false,
        "overrideSearchPages": false
    },
    "termLists": [],
    "urlFilters": {
        "noPageModify": [],
        "nonSearch": []
    }
}
```

**Comment by ator-dev** [comment] 2023-07-23 12:05
Sorry, I forgot to update you on this. Your last comment led me to the source of the issue: for whatever reason, on Chromium browsers only, *clicking* a match option from the list does not correctly send an update message. I never noticed this because I use different matching strategy selection methods, which are unaffected by the issue.

1. Instead of clicking on the meatballs button, pull down from the button or the keyword, then release your mouse over the option you want.
2. After opening a menu - either by mouse or by shortcut (Shift+Space) - press the underlined key.

I have been rewriting the code that deals with this part of MMS, to make it easier to maintain. Unfortunately I burnt myself out, so I'm taking a break doing some more creative things at the moment. Sorry for the wait, an update will be available later :sweat_smile:

**Comment by ator-dev** [comment] 2023-11-18 17:00
Hello again, it's been a long wait but I am starting work on Mark My Search again. My first priority is finishing some in-progress work, including the one that addresses this issue among other problems!

The matching strategy menu has been completely reworked, allowing the user to select multiple options without closing the menu, and being generally nicer to use:

![image](https://github.com/searchmarkers/mark-my-search/assets/66553618/63239d5a-ba44-4a69-99e0-529a3d302274)

I also fixed some long-standing problems with the toolbar.

*Note: There is still an unresolved problem on Chrome/ium, but it doesn't affect the experience much.*

**Closed by ator-dev** 2023-11-18 17:00 UTC
Labels: bug, planned
