### ISSUE TITLE
As a user I want highlight parity across text/image/video search pages ENHANCEMENT

### ISSUE THREAD

**Issue by ldexterldesign** [searchmarkers/mark-my-search#113] opened 2023-04-12 17:41 UTC
👋

Thanks for great software

Sorry for brevity right now 😞

I hope these two screenshots highlight (excuse the pun) the problem but if not then happy to elaborate later

<img width="1840" alt="Screenshot 2023-04-12 at 18 36 33" src="https://user-images.githubusercontent.com/1715809/231539159-be4b21b2-ca42-470e-9c0a-fbd9062afc2d.png">

<img width="1840" alt="Screenshot 2023-04-12 at 18 36 38" src="https://user-images.githubusercontent.com/1715809/231539204-bd63adf3-a65c-42d3-a4ec-f3ca6fac2e34.png">

Hope this helps!

Sincerely

**Comment by ator-dev** [comment] 2023-04-12 21:23
Hi, no worries about the brevity! Thank you for reporting this issue, it has come to my attention before but I finally managed to solve it*. The fix will be published in version __1.13.4__.

Fixed by #114 

*Note that no highlighting model can be perfect; however, Mark My Search now does extremely well at responding to interference with its highlighting.

**Comment by ldexterldesign** [comment] 2023-04-12 21:27
👍👍

**Comment by ator-dev** [comment] 2023-04-15 09:48
Shipped with __1.13.4__, now available in the Chrome Web Store and pending for Edge (Firefox version to be updated when ported)

**Comment by ldexterldesign** [comment] 2023-04-15 13:16
👏

Unsure of the search engine support - be interested to know or have something in the README..?

After testing, seems to function fully in [google.com/search] but not in [search.brave.com]..?

Hope this helps

Sincerely

[search.brave.com]: http://search.brave.com/images?q=food&source=web
[google.com/search]: http://google.com/search?q=food

**Comment by ator-dev** [comment] 2023-04-15 18:31
Hey,

I have some good news! I looked into your new issue (this 'Brave images' problem is different but related to the original one you reported), and determined it was another programming flaw in the CLASSIC highlighter.

I was not only able to fix the problem - making the highlighter work _as intended_ everywhere - but also massively optimised it, and in the process made scroll markers able to update much more quickly. You should see improvements in many areas of use when this update ships (in __1.13.5__).

---

As for search engine support, the idea has always been that __every search engine is supported__. That's how I explain MMS to people, and it's important to me that we don't rely on 'special cases'. However, it is becoming clear that in practice, some sites just don't work as intended.

What do you think about having a list of search engines which are officially supported? "Officially" meaning it may work in other places, but it is __guaranteed__ to be tested and designed for those ones.

Example (I know these to work reasonably well):

- DuckDuckGo
- Brave
- Ecosia
- Google
- Bing
- Yandex
- Reddit search
- eBay search
- Amazon search
- Netflix search
- (would probably add more)

**Comment by ldexterldesign** [comment] 2023-04-15 22:15
Glad to help 🙂

Ya, having a checklist of supported websites should help manage user expectation and encourage them to a) submit new websites and/or b) report issues for the supported websites

You're brave to go beyond search engines (e.g. amazon, ebay, reddit, netflix) as it could be opening a can of worms 😱 - perhaps open a new issue and gauge interest first..?

Cheers

**Closed** 2023-04-16 12:47 UTC
Labels: bug

**Comment by ator-dev** [comment] 2023-04-16 12:50
Oops, automatically closed. I won't reopen for now because I think the issue was solved, but please let me know if it persists after upgrading to __1.13.5__ or later (currently pending review on Chrome Web Store).

Thanks very much for your input, I like the idea of maintaining a list of "supported" search engines and will certainly look into presenting one here! I will also weigh up the benefits of including site searches (like reddit).

**Comment by ator-dev** [comment] 2023-04-16 14:07
Note: unfortunately I made a critical mistake in #116, and will need to wait for it to finish review in CWS before I can push __1.13.6__ which will bring the improvements along with a fix for the mistake (#117).
